import { promises as fs } from "node:fs";
import * as fsSync from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { z } from "zod";
import type { PendingBlocker } from "@cloakcode/protocol";
import { isInteractiveTool, toConfirmations } from "./session-observer.js";

/**
 * The extension↔hook contract. The spool is a **directory**, one file per live
 * blocker named `<baseToolCallId>.json` (localhost/fs only — never the network).
 * The hook WRITES the file on `PreToolUse` and DELETES it on `PostToolUse`, so a
 * blocker is pending iff its file exists. One-file-per-record means concurrent
 * hooks (multiple windows sharing a user-global spool dir) never race on a
 * shared append log. See docs/03 "Deployment & concurrency".
 */
export const spoolRecordSchema = z.object({
  sessionId: z.string(),
  toolCallId: z.string(),
  toolName: z.string(),
  input: z.unknown().optional(),
  ts: z.string(),
});
export type SpoolRecord = z.infer<typeof spoolRecordSchema>;

/**
 * The spool directory. This is the SINGLE source of truth for where blockers
 * live, computed identically by both the hook and every window's follower, so
 * they can never diverge. It is a **fixed, per-environment** path (not
 * `globalStorageUri`, which is per-profile): the hook config is one user-global
 * file that fires for every window/profile in the environment, so the one spool
 * path it writes to must be the same one every follower reads — a per-profile
 * dir would leave other windows watching the wrong place (no updates).
 */
export function defaultSpoolDir(): string {
  return path.join(os.homedir(), ".cloakcode", "spool");
}

/**
 * Build the user-global hook config the extension self-installs. Uses ABSOLUTE
 * paths only — `runtime` (`process.execPath`, the node running the extension
 * host, always present), the bundled `hookBin`, and the `spoolDir` — so it works
 * with no `node`-on-PATH assumption and no workspace/`.local` hardcoding. Pure so
 * it's tested without touching the filesystem. See docs/03 "Deployment".
 */
export function buildHookConfig(opts: {
  runtime: string;
  hookBin: string;
  spoolDir: string;
}): unknown {
  // No need to pass CLOAKCODE_SPOOL for the standard location — the hook derives
  // the same `defaultSpoolDir()` itself, so the config stays minimal and there's
  // nothing to drift. Only emit it when overridden (dev-server / isolated rig).
  const isDefault = opts.spoolDir === defaultSpoolDir();
  const entry = (event: string): unknown => ({
    type: "command",
    command: `"${opts.runtime}" "${opts.hookBin}" ${event}`,
    timeout: 30,
    ...(isDefault ? {} : { env: { CLOAKCODE_SPOOL: opts.spoolDir } }),
  });
  return {
    "//":
      "Auto-generated by the CloakCode extension: bundled notifier + this env's node + " +
      "the shared ~/.cloakcode/spool dir. Non-intrusive (no permissionDecision). Safe to " +
      "delete; rewritten on activate.",
    hooks: {
      PreToolUse: [entry("PreToolUse")],
      PostToolUse: [entry("PostToolUse")],
    },
  };
}

/**
 * Strip the `__vscode-<n>` suffix the hook receives so the id matches the
 * transcript's `toolCallId` (docs/02 §4.6 — this is the dedup join key) and
 * yields a stable, filesystem-safe spool filename.
 */
export function baseToolCallId(raw: string): string {
  const i = raw.indexOf("__vscode-");
  return i === -1 ? raw : raw.slice(0, i);
}

/** Path of the spool entry file for a (raw or base) toolCallId. */
export function spoolEntryPath(dir: string, toolCallId: string): string {
  return path.join(dir, `${baseToolCallId(toolCallId)}.json`);
}

/**
 * Build the pending record for a `PreToolUse` invocation, or `undefined` when
 * the event lacks routing keys. Pure so the hook's I/O shell stays trivial and
 * tested. (`PostToolUse` needs no record — the hook just deletes the file.)
 */
export function pendingRecord(
  stdin: unknown,
  ts: string,
): SpoolRecord | undefined {
  const s = (typeof stdin === "object" && stdin ? stdin : {}) as Record<
    string,
    unknown
  >;
  const sessionId = String(s["session_id"] ?? "");
  const rawId = String(s["tool_use_id"] ?? "");
  const toolName = String(s["tool_name"] ?? "");
  // Only interactive tools are blockers worth surfacing (docs/02 §4.6). Skipping
  // the rest means non-blocker tool calls (read_file, grep, …) never touch the
  // spool — no write/delete churn, and the overlay can't flicker a non-blocker.
  if (!sessionId || !rawId || !isInteractiveTool(toolName)) return undefined;
  return {
    sessionId,
    toolCallId: baseToolCallId(rawId),
    toolName,
    input: s["tool_input"] ?? null,
    ts,
  };
}

/** The base toolCallId a hook event refers to (for the delete path). */
export function eventToolCallId(stdin: unknown): string | undefined {
  const s = (typeof stdin === "object" && stdin ? stdin : {}) as Record<
    string,
    unknown
  >;
  const rawId = String(s["tool_use_id"] ?? "");
  return rawId ? baseToolCallId(rawId) : undefined;
}

/** Read all valid spool records from the spool directory (tolerant of junk). */
export async function readSpoolDir(dir: string): Promise<SpoolRecord[]> {
  let names: string[];
  try {
    names = await fs.readdir(dir);
  } catch {
    return [];
  }
  const out: SpoolRecord[] = [];
  for (const name of names) {
    if (!name.endsWith(".json")) continue;
    let raw: unknown;
    try {
      raw = JSON.parse(await fs.readFile(path.join(dir, name), "utf8"));
    } catch {
      continue; // partial write / junk — skip, a later refresh will catch it
    }
    const parsed = spoolRecordSchema.safeParse(raw);
    if (parsed.success) out.push(parsed.data);
  }
  return out;
}

/** Collect the base `toolCallId`s already present in a transcript body. */
export function transcriptToolCallIds(content: string): Set<string> {
  const ids = new Set<string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    let raw: { type?: string; data?: { toolCallId?: unknown } };
    try {
      raw = JSON.parse(trimmed);
    } catch {
      continue;
    }
    if (raw.type === "tool.execution_start" && raw.data?.toolCallId != null) {
      ids.add(baseToolCallId(String(raw.data.toolCallId)));
    }
  }
  return ids;
}

/**
 * A spool record is _retired_ once its tool has landed in the transcript (its
 * base `toolCallId` appears there). Per §4.6 interactive events flush at
 * completion, so transcript presence ⟹ the tool finished — the single source of
 * truth for "this blocker is done", used both to drop it from the overlay and to
 * self-heal a spool file whose `PostToolUse` delete failed.
 */
export function isRetired(
  record: SpoolRecord,
  transcriptIds: ReadonlySet<string>,
): boolean {
  return transcriptIds.has(baseToolCallId(record.toolCallId));
}

/**
 * Compute the live-pending overlay for one session: every spool record for that
 * session (each file = a live blocker), minus any already flushed to the
 * transcript (belt-and-suspenders dedup so a missed delete can't strand a card).
 * Replace-snapshot semantics — the caller pushes the whole list.
 */
export function computePendingBlockers(
  records: readonly SpoolRecord[],
  sessionId: string,
  transcriptIds: ReadonlySet<string> = new Set(),
): PendingBlocker[] {
  const pending = new Map<string, PendingBlocker>();
  for (const r of records) {
    if (r.sessionId !== sessionId) continue;
    if (isRetired(r, transcriptIds)) continue;
    const base = baseToolCallId(r.toolCallId);
    pending.set(base, {
      toolCallId: base,
      toolName: r.toolName,
      createdAt: r.ts,
      ...(isInteractiveTool(r.toolName)
        ? { confirmations: toConfirmations(`conf-${base}`, r.input) }
        : { input: r.input ?? null }),
    });
  }
  return [...pending.values()];
}

export type PendingSink = (blockers: PendingBlocker[]) => void;

async function readOrEmpty(file: string): Promise<string> {
  try {
    return await fs.readFile(file, "utf8");
  } catch {
    return "";
  }
}

/**
 * Tails the (global) hook spool DIRECTORY and the subscribed session's
 * transcript, and emits the live-pending overlay as a replace-snapshot for that
 * session. Mirrors `SessionFollower`'s hybrid `fs.watch` + poll strategy
 * (dev-container overlays drop inotify events) and serializes on a promise
 * queue. Emits only when the snapshot changes. Recompute is triggered by EITHER
 * the spool dir or the transcript changing.
 */
export class SpoolFollower {
  private watchers: fsSync.FSWatcher[] = [];
  private poller: ReturnType<typeof setInterval> | undefined;
  private queue: Promise<void> = Promise.resolve();
  private stopped = false;
  private last: string | undefined;
  private readonly pollIntervalMs: number;

  constructor(
    private readonly spoolDir: string,
    private readonly transcriptFile: string,
    private readonly sessionId: string,
    private readonly sink: PendingSink,
    options: { pollIntervalMs?: number } = {},
  ) {
    this.pollIntervalMs = options.pollIntervalMs ?? 400;
  }

  async start(): Promise<void> {
    await this.refresh();
    if (this.stopped) return;
    for (const target of [this.spoolDir, this.transcriptFile]) {
      try {
        this.watchers.push(fsSync.watch(target, () => void this.refresh()));
      } catch {
        // dir/file may not exist yet; the poll fallback covers it
      }
    }
    if (this.pollIntervalMs > 0) {
      this.poller = setInterval(() => void this.refresh(), this.pollIntervalMs);
      this.poller.unref();
    }
  }

  refresh(): Promise<void> {
    this.queue = this.queue.then(() => this.pump());
    return this.queue;
  }

  private async pump(): Promise<void> {
    if (this.stopped) return;
    const records = await readSpoolDir(this.spoolDir);
    if (this.stopped) return;
    const mine = records.filter((r) => r.sessionId === this.sessionId);

    // Fast path: no spool file for this session → nothing is pending, so skip
    // reading and parsing the (potentially large) transcript entirely.
    if (mine.length === 0) {
      this.emit([]);
      return;
    }

    const transcriptIds = transcriptToolCallIds(
      await readOrEmpty(this.transcriptFile),
    );
    if (this.stopped) return;

    // Self-heal: a spool file whose tool already completed (its toolCallId is in
    // the transcript — §4.6, interactive events land there at completion) is
    // stale; the hook's PostToolUse delete must have failed. Unlink it so it
    // stops costing dedup compute on every pump instead of lingering forever.
    // (Idempotent under concurrent followers; the dedup below already hides it.)
    const stale = mine.filter((r) => isRetired(r, transcriptIds));
    await Promise.all(
      stale.map((r) =>
        fs
          .rm(spoolEntryPath(this.spoolDir, r.toolCallId), { force: true })
          .catch(() => {
            // best-effort — the transcript-subtraction dedup keeps it invisible
          }),
      ),
    );
    if (this.stopped) return;

    this.emit(computePendingBlockers(mine, this.sessionId, transcriptIds));
  }

  private emit(blockers: PendingBlocker[]): void {
    const snapshot = JSON.stringify(blockers);
    if (snapshot === this.last) return;
    this.last = snapshot;
    this.sink(blockers);
  }

  stop(): void {
    this.stopped = true;
    for (const w of this.watchers) w.close();
    this.watchers = [];
    if (this.poller) {
      clearInterval(this.poller);
      this.poller = undefined;
    }
  }
}
