import { promises as fs } from "node:fs";
import * as fsSync from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { z } from "zod";
import type { PendingBlocker, QuestionAnswer } from "@cloakcode/protocol";
import { isInteractiveTool, toConfirmations } from "./session-observer.js";

/**
 * The extension↔hook contract. The spool is a **directory**, one file per live
 * blocker named `<baseToolCallId>.json` (localhost/fs only — never the network).
 * The hook WRITES the file on `PreToolUse` and DELETES it on `PostToolUse`, so a
 * blocker is pending iff its file exists. One-file-per-record means concurrent
 * hooks (multiple windows sharing a user-global spool dir) never race on a
 * shared append log. See docs/03 "Deployment & concurrency".
 */
export const spoolRecordSchema = z.object({
  sessionId: z.string(),
  toolCallId: z.string(),
  toolName: z.string(),
  input: z.unknown().optional(),
  ts: z.string(),
  awaitingDecision: z.boolean().optional(),
  // The RAW `tool_use_id` (with the `__vscode-<n>` suffix intact) — the carousel
  // `resolveId` used to answer a question structurally (docs/02 §4.16).
  resolveId: z.string().optional(),
});
export type SpoolRecord = z.infer<typeof spoolRecordSchema>;

/**
 * The spool directory. This is the SINGLE source of truth for where blockers
 * live, computed identically by both the hook and every window's follower, so
 * they can never diverge. It is a **fixed, per-environment** path (not
 * `globalStorageUri`, which is per-profile): the hook config is one user-global
 * file that fires for every window/profile in the environment, so the one spool
 * path it writes to must be the same one every follower reads — a per-profile
 * dir would leave other windows watching the wrong place (no updates).
 */
export function defaultSpoolDir(): string {
  return path.join(os.homedir(), ".cloakcode", "spool");
}

/**
 * The VS Code chat-session resource URI for a local Copilot session id - byte
 * for byte what `LocalChatSessionUri.forSession` builds (vscode chatUri.ts): the
 * `vscode-chat-session` scheme, `local` authority, and the id as UNPADDED
 * base64url. Used to target ONE session for `acceptTool`/`skipTool` and
 * `vscode.open`. VS Code matches it by EXACT URI equality, so a wrong or empty
 * id can only fail to match (a safe no-op) and never resolves a DIFFERENT
 * session. Verified against vscode source 2026-07-10 (docs/02 4.16).
 */
export function localChatSessionUri(sessionId: string): string {
  return `vscode-chat-session://local/${Buffer.from(sessionId).toString(
    "base64url",
  )}`;
}

/**
 * Build the user-global hook config the extension self-installs. Uses ABSOLUTE
 * paths only — `runtime` (`process.execPath`, the node running the extension
 * host, always present), the bundled `hookBin`, and the `spoolDir` — so it works
 * with no `node`-on-PATH assumption and no workspace/`.local` hardcoding. Pure so
 * it's tested without touching the filesystem. See docs/03 "Deployment".
 */
export function buildHookConfig(opts: {
  runtime: string;
  hookBin: string;
  spoolDir: string;
}): unknown {
  // No need to pass CLOAKCODE_SPOOL for the standard location — the hook derives
  // the same `defaultSpoolDir()` itself, so the config stays minimal and there's
  // nothing to drift. Only emit it when overridden (dev-server / isolated rig).
  const isDefault = opts.spoolDir === defaultSpoolDir();
  const entry = (event: string, timeout: number): unknown => ({
    type: "command",
    command: `"${opts.runtime}" "${opts.hookBin}" ${event}`,
    timeout,
    ...(isDefault ? {} : { env: { CLOAKCODE_SPOOL: opts.spoolDir } }),
  });
  return {
    "//":
      "Auto-generated by the CloakCode extension: bundled hook + this env's node + the shared " +
      "~/.cloakcode/spool dir. A pure NOTIFIER: it emits no permissionDecision and never blocks; it " +
      "only records live tool calls so the CloakCode client can surface and resolve them. " +
      "Safe to delete; rewritten on activate.",
    hooks: {
      PreToolUse: [entry("PreToolUse", 30)],
      PostToolUse: [entry("PostToolUse", 30)],
    },
  };
}

/**
 * A core carousel answer value (`IChatQuestionAnswerValue`). The shape must
 * match the question TYPE or VS Code won't RENDER the choice (the tool result is
 * type-tolerant, but the carousel display is not): `singleSelect` uses
 * `selectedValue`, `multiSelect` uses `selectedValues`, freeform uses
 * `freeformValue` (`askQuestionsTool.ts::convertCarouselAnswers`).
 */
export interface CarouselAnswerValue {
  selectedValue?: string;
  selectedValues?: string[];
  freeformValue?: string;
}

/**
 * Build the core carousel answer record for `_chat.notifyQuestionCarouselAnswer`
 * from CloakCode's per-question `answers` (docs/02 §4.16), keyed by the internal
 * question id `${resolveId}:${index}`. Picks the value shape by intent so VS
 * Code renders it: a typed freeform value → `freeformValue`; a single chosen
 * option → `selectedValue` (singular = single-select); multiple →
 * `selectedValues`. Pure.
 */
export function buildCarouselAnswers(
  resolveId: string,
  answers: readonly QuestionAnswer[],
): Record<string, CarouselAnswerValue> {
  const record: Record<string, CarouselAnswerValue> = {};
  answers.forEach((a, i) => {
    const key = `${resolveId}:${i}`;
    if (a.multiSelect) {
      record[key] = {
        selectedValues: a.selected,
        ...(a.freeText ? { freeformValue: a.freeText } : {}),
      };
    } else if (a.freeText) {
      record[key] = { freeformValue: a.freeText };
    } else {
      const only = a.selected[0];
      record[key] =
        only !== undefined
          ? { selectedValue: only }
          : { selectedValues: a.selected };
    }
  });
  return record;
}

/**
 * Strip the `__vscode-<n>` suffix the hook receives so the id matches the
 * transcript's `toolCallId` (docs/02 §4.6 — this is the dedup join key) and
 * yields a stable, filesystem-safe spool filename.
 */
export function baseToolCallId(raw: string): string {
  const i = raw.indexOf("__vscode-");
  return i === -1 ? raw : raw.slice(0, i);
}

/** Path of the spool entry file for a (raw or base) toolCallId. */
export function spoolEntryPath(dir: string, toolCallId: string): string {
  return path.join(dir, `${baseToolCallId(toolCallId)}.json`);
}

/**
 * Extract the routing keys the hook cares about from a `PreToolUse`/`PostToolUse`
 * stdin payload (`{ session_id, tool_name, tool_use_id, tool_input }`). Shared by
 * every record builder so the field names live in exactly one place.
 */
export function hookRouting(stdin: unknown): {
  sessionId: string;
  toolName: string;
  rawId: string;
  input: unknown;
  transcriptPath: string;
} {
  const s = (typeof stdin === "object" && stdin ? stdin : {}) as Record<
    string,
    unknown
  >;
  return {
    sessionId: String(s["session_id"] ?? ""),
    toolName: String(s["tool_name"] ?? ""),
    rawId: String(s["tool_use_id"] ?? ""),
    input: s["tool_input"] ?? null,
    transcriptPath: String(s["transcript_path"] ?? ""),
  };
}

/**
 * Build the spool record for a `PreToolUse` invocation, or `undefined` when the
 * event lacks routing keys. EVERY tool call is surfaced: the hook runs upstream
 * of VS Code's approve/confirm decision, so it cannot know which calls need
 * confirming; the observer debounces surfacing so auto-approved calls never show
 * (docs/02 4.20). An interactive tool (ask/confirm/input/...) becomes a QUESTION;
 * anything else an APPROVAL (`awaitingDecision`, rendered allow/deny). Pure so
 * the hook I/O shell stays trivial and tested. (`PostToolUse` needs no record;
 * the hook just deletes the file.)
 */
export function spoolRecordFor(
  stdin: unknown,
  ts: string,
): SpoolRecord | undefined {
  const { sessionId, toolName, rawId, input } = hookRouting(stdin);
  if (!sessionId || !rawId) return undefined;
  return {
    sessionId,
    toolCallId: baseToolCallId(rawId),
    toolName,
    input,
    ts,
    // The one behavioural split left: interactive tools are answered (question
    // carousel); everything else is an allow/deny approval.
    ...(isInteractiveTool(toolName) ? {} : { awaitingDecision: true }),
    resolveId: rawId,
  };
}

/** The base toolCallId a hook event refers to (for the delete path). */
export function eventToolCallId(stdin: unknown): string | undefined {
  const { rawId } = hookRouting(stdin);
  return rawId ? baseToolCallId(rawId) : undefined;
}

/** Read all valid spool records from the spool directory (tolerant of junk). */
export async function readSpoolDir(dir: string): Promise<SpoolRecord[]> {
  let names: string[];
  try {
    names = await fs.readdir(dir);
  } catch {
    return [];
  }
  const out: SpoolRecord[] = [];
  for (const name of names) {
    if (!name.endsWith(".json")) continue;
    let raw: unknown;
    try {
      raw = JSON.parse(await fs.readFile(path.join(dir, name), "utf8"));
    } catch {
      continue; // partial write / junk — skip, a later refresh will catch it
    }
    const parsed = spoolRecordSchema.safeParse(raw);
    if (parsed.success) out.push(parsed.data);
  }
  return out;
}

/** Collect the base `toolCallId`s already present in a transcript body. */
export function transcriptToolCallIds(content: string): Set<string> {
  const ids = new Set<string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    let raw: { type?: string; data?: { toolCallId?: unknown } };
    try {
      raw = JSON.parse(trimmed);
    } catch {
      continue;
    }
    if (raw.type === "tool.execution_start" && raw.data?.toolCallId != null) {
      ids.add(baseToolCallId(String(raw.data.toolCallId)));
    }
  }
  return ids;
}

/**
 * The newest turn-boundary timestamp in a transcript body: the max ISO
 * `timestamp` over `user.message` + `assistant.turn_start` events (a turn
 * beginning). Used to retire a spool blocker the session has moved PAST. Tool
 * events are deliberately ignored so a sibling tool finishing in the SAME turn
 * cannot retire a still-live approval. Timestamps are NOT monotonic across
 * history, so this takes the MAX (an old out-of-order event cannot inflate it);
 * only a genuinely later turn supersedes. Causal, never a wall-clock TTL. See
 * docs/02 4.19.
 */
export function newestTurnTs(content: string): string | undefined {
  let newest: string | undefined;
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    let raw: { type?: string; timestamp?: unknown };
    try {
      raw = JSON.parse(trimmed);
    } catch {
      continue;
    }
    if (raw.type === "user.message" || raw.type === "assistant.turn_start") {
      const ts = typeof raw.timestamp === "string" ? raw.timestamp : undefined;
      if (ts && (newest === undefined || ts > newest)) newest = ts;
    }
  }
  return newest;
}

/**
 * A spool record is _retired_ once its tool has landed in the transcript (its
 * base `toolCallId` appears there). Per §4.6 interactive events flush at
 * completion, so transcript presence ⟹ the tool finished — the single source of
 * truth for "this blocker is done", used both to drop it from the overlay and to
 * self-heal a spool file whose `PostToolUse` delete failed.
 */
export function isRetired(
  record: SpoolRecord,
  transcriptIds: ReadonlySet<string>,
): boolean {
  return transcriptIds.has(baseToolCallId(record.toolCallId));
}

/**
 * A spool record is _superseded_ once the session has advanced to a LATER turn
 * than when the blocker was recorded (`newestTurn` > the record's `ts`). This
 * clears an orphaned card - a tool call with no end because the turn was
 * cancelled or the window closed before `PostToolUse` - the moment new activity
 * happens, with no restart and no timer. A genuinely LIVE blocker is safe: the
 * transcript lags the in-flight turn (4.6), so its turn events are OLDER than the
 * record and nothing supersedes it until the session really moves on. See
 * docs/02 4.19.
 */
export function isSuperseded(
  record: SpoolRecord,
  newestTurn: string | undefined,
): boolean {
  return newestTurn !== undefined && newestTurn > record.ts;
}

/**
 * Compute the live-pending overlay for one session: every spool record for that
 * session (each file = a live blocker), minus any already flushed to the
 * transcript (belt-and-suspenders dedup so a missed delete can't strand a card).
 * Replace-snapshot semantics — the caller pushes the whole list.
 */
export function computePendingBlockers(
  records: readonly SpoolRecord[],
  sessionId: string,
  transcriptIds: ReadonlySet<string> = new Set(),
  newestTurn?: string,
): PendingBlocker[] {
  const pending = new Map<string, PendingBlocker>();
  for (const r of records) {
    if (r.sessionId !== sessionId) continue;
    if (isRetired(r, transcriptIds)) continue;
    if (isSuperseded(r, newestTurn)) continue;
    const base = baseToolCallId(r.toolCallId);
    pending.set(base, {
      toolCallId: base,
      toolName: r.toolName,
      createdAt: r.ts,
      ...(r.awaitingDecision ? { awaitingDecision: true } : {}),
      ...(r.resolveId ? { resolveId: r.resolveId } : {}),
      ...(isInteractiveTool(r.toolName)
        ? { confirmations: toConfirmations(`conf-${base}`, r.input) }
        : { input: r.input ?? null }),
    });
  }
  return [...pending.values()];
}

export type PendingSink = (blockers: PendingBlocker[]) => void;

async function readOrEmpty(file: string): Promise<string> {
  try {
    return await fs.readFile(file, "utf8");
  } catch {
    return "";
  }
}

/**
 * Tails the (global) hook spool DIRECTORY and the subscribed session's
 * transcript, and emits the live-pending overlay as a replace-snapshot for that
 * session. Mirrors `SessionFollower`'s hybrid `fs.watch` + poll strategy
 * (dev-container overlays drop inotify events) and serializes on a promise
 * queue. Emits only when the snapshot changes. Recompute is triggered by EITHER
 * the spool dir or the transcript changing.
 */
export class SpoolFollower {
  private watchers: fsSync.FSWatcher[] = [];
  private poller: ReturnType<typeof setInterval> | undefined;
  private queue: Promise<void> = Promise.resolve();
  private stopped = false;
  private last: string | undefined;
  private readonly pollIntervalMs: number;
  private readonly debounceMs: number;
  private readonly now: () => number;
  private debounceTimer: ReturnType<typeof setTimeout> | undefined;

  constructor(
    private readonly spoolDir: string,
    private readonly transcriptFile: string,
    private readonly sessionId: string,
    private readonly sink: PendingSink,
    options: {
      pollIntervalMs?: number;
      debounceMs?: number;
      now?: () => number;
    } = {},
  ) {
    this.pollIntervalMs = options.pollIntervalMs ?? 400;
    // Debounce is OFF unless a caller passes one. The extension passes the
    // `cloakcode.surfaceDebounceMs` setting, whose package.json default (3 s) is
    // the single source of truth; the dev-server/tests opt in explicitly.
    this.debounceMs = options.debounceMs ?? 0;
    this.now = options.now ?? Date.now;
  }

  async start(): Promise<void> {
    await this.refresh();
    if (this.stopped) return;
    for (const target of [this.spoolDir, this.transcriptFile]) {
      try {
        this.watchers.push(fsSync.watch(target, () => void this.refresh()));
      } catch {
        // dir/file may not exist yet; the poll fallback covers it
      }
    }
    if (this.pollIntervalMs > 0) {
      this.poller = setInterval(() => void this.refresh(), this.pollIntervalMs);
      this.poller.unref();
    }
  }

  refresh(): Promise<void> {
    this.queue = this.queue.then(() => this.pump());
    return this.queue;
  }

  private async pump(): Promise<void> {
    if (this.stopped) return;
    const records = await readSpoolDir(this.spoolDir);
    if (this.stopped) return;
    const mine = records.filter((r) => r.sessionId === this.sessionId);

    // Fast path: no spool file for this session → nothing is pending, so skip
    // reading and parsing the (potentially large) transcript entirely.
    if (mine.length === 0) {
      this.scheduleDebounce(undefined);
      this.emit([]);
      return;
    }

    const content = await readOrEmpty(this.transcriptFile);
    const transcriptIds = transcriptToolCallIds(content);
    const newestTurn = newestTurnTs(content);
    if (this.stopped) return;

    // Self-heal: a spool file whose tool already completed (its toolCallId is in
    // the transcript — §4.6, interactive events land there at completion) is
    // stale; the hook's PostToolUse delete must have failed. Unlink it so it
    // stops costing dedup compute on every pump instead of lingering forever.
    // (Idempotent under concurrent followers; the dedup below already hides it.)
    const stale = mine.filter(
      (r) => isRetired(r, transcriptIds) || isSuperseded(r, newestTurn),
    );
    await Promise.all(
      stale.map((r) =>
        fs
          .rm(spoolEntryPath(this.spoolDir, r.toolCallId), { force: true })
          .catch(() => {
            // best-effort — the transcript-subtraction dedup keeps it invisible
          }),
      ),
    );
    if (this.stopped) return;

    // Debounce SURFACING: a call VS Code auto-approves/answers completes within
    // the debounce and is retired above before it ever shows (no flicker). A call
    // still pending after the debounce IS surfaced (the client flags that it may
    // already be resolved). Non-stale calls not yet mature arm a re-pump so they
    // surface on time even if nothing else touches the spool/transcript.
    const now = this.now();
    const staleIds = new Set(stale.map((r) => baseToolCallId(r.toolCallId)));
    const ageOf = (r: SpoolRecord): number => {
      const created = Date.parse(r.ts);
      return Number.isNaN(created) ? Infinity : now - created;
    };
    const mature = mine.filter((r) => ageOf(r) >= this.debounceMs);
    const waits = mine
      .filter(
        (r) =>
          !staleIds.has(baseToolCallId(r.toolCallId)) &&
          ageOf(r) < this.debounceMs,
      )
      .map((r) => this.debounceMs - ageOf(r));
    this.scheduleDebounce(
      waits.length ? Math.max(0, Math.min(...waits)) : undefined,
    );

    this.emit(
      computePendingBlockers(mature, this.sessionId, transcriptIds, newestTurn),
    );
  }

  private emit(blockers: PendingBlocker[]): void {
    const snapshot = JSON.stringify(blockers);
    if (snapshot === this.last) return;
    this.last = snapshot;
    this.sink(blockers);
  }

  /** (Re)arm the one-shot re-pump that surfaces a call once it clears the debounce. */
  private scheduleDebounce(waitMs: number | undefined): void {
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
      this.debounceTimer = undefined;
    }
    if (waitMs === undefined || this.stopped) return;
    this.debounceTimer = setTimeout(() => {
      this.debounceTimer = undefined;
      void this.refresh();
    }, waitMs);
    this.debounceTimer.unref();
  }

  stop(): void {
    this.stopped = true;
    for (const w of this.watchers) w.close();
    this.watchers = [];
    if (this.poller) {
      clearInterval(this.poller);
      this.poller = undefined;
    }
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
      this.debounceTimer = undefined;
    }
  }
}
