import { promises as fs } from "node:fs";
import * as fsSync from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { z } from "zod";
import { decisionSchema } from "@cloakcode/protocol";
import type {
  Decision,
  PendingBlocker,
  QuestionAnswer,
} from "@cloakcode/protocol";
import { isInteractiveTool, toConfirmations } from "./session-observer.js";

/**
 * The extension↔hook contract. The spool is a **directory**, one file per live
 * blocker named `<baseToolCallId>.json` (localhost/fs only — never the network).
 * The hook WRITES the file on `PreToolUse` and DELETES it on `PostToolUse`, so a
 * blocker is pending iff its file exists. One-file-per-record means concurrent
 * hooks (multiple windows sharing a user-global spool dir) never race on a
 * shared append log. See docs/03 "Deployment & concurrency".
 */
export const spoolRecordSchema = z.object({
  sessionId: z.string(),
  toolCallId: z.string(),
  toolName: z.string(),
  input: z.unknown().optional(),
  ts: z.string(),
  awaitingDecision: z.boolean().optional(),
  // The RAW `tool_use_id` (with the `__vscode-<n>` suffix intact) — the carousel
  // `resolveId` used to answer a question structurally (docs/02 §4.16).
  resolveId: z.string().optional(),
});
export type SpoolRecord = z.infer<typeof spoolRecordSchema>;

/**
 * The spool directory. This is the SINGLE source of truth for where blockers
 * live, computed identically by both the hook and every window's follower, so
 * they can never diverge. It is a **fixed, per-environment** path (not
 * `globalStorageUri`, which is per-profile): the hook config is one user-global
 * file that fires for every window/profile in the environment, so the one spool
 * path it writes to must be the same one every follower reads — a per-profile
 * dir would leave other windows watching the wrong place (no updates).
 */
export function defaultSpoolDir(): string {
  return path.join(os.homedir(), ".cloakcode", "spool");
}

/**
 * PreToolUse hook timeout (seconds). Copilot blocks on the hook synchronously
 * for up to this long, so it also caps a take-control blocking wait; the poll
 * (see {@link awaitDecision}) uses a slightly shorter budget so a timed-out
 * approval falls through to native BEFORE Copilot kills the hook. The common
 * (notify/defer) path returns in milliseconds — this only bites while actually
 * holding a call for a remote decision.
 */
export const BLOCK_HOOK_TIMEOUT_SECONDS = 120;

/**
 * Build the user-global hook config the extension self-installs. Uses ABSOLUTE
 * paths only — `runtime` (`process.execPath`, the node running the extension
 * host, always present), the bundled `hookBin`, and the `spoolDir` — so it works
 * with no `node`-on-PATH assumption and no workspace/`.local` hardcoding. Pure so
 * it's tested without touching the filesystem. See docs/03 "Deployment".
 */
export function buildHookConfig(opts: {
  runtime: string;
  hookBin: string;
  spoolDir: string;
}): unknown {
  // No need to pass CLOAKCODE_SPOOL for the standard location — the hook derives
  // the same `defaultSpoolDir()` itself, so the config stays minimal and there's
  // nothing to drift. Only emit it when overridden (dev-server / isolated rig).
  const isDefault = opts.spoolDir === defaultSpoolDir();
  const entry = (event: string, timeout: number): unknown => ({
    type: "command",
    command: `"${opts.runtime}" "${opts.hookBin}" ${event}`,
    timeout,
    ...(isDefault ? {} : { env: { CLOAKCODE_SPOOL: opts.spoolDir } }),
  });
  return {
    "//":
      "Auto-generated by the CloakCode extension: bundled hook + this env's node + the shared " +
      "~/.cloakcode/spool dir. A pure notifier by default (emits no permissionDecision); only holds " +
      "a tool call for a remote allow/deny when the operator has taken control of the session. " +
      "Safe to delete; rewritten on activate.",
    hooks: {
      PreToolUse: [entry("PreToolUse", BLOCK_HOOK_TIMEOUT_SECONDS)],
      PostToolUse: [entry("PostToolUse", 30)],
    },
  };
}

// ---------------------------------------------------------------------------
// Take-control: per-session policy, the pre-tool decision, on-disk approval
// verdicts, and the blocking poll. All pure/injectable so hook.ts stays a thin
// I/O shell. See docs/03 "Blocking-hook handoff" + docs/04 (provenance).
// ---------------------------------------------------------------------------

/**
 * The extension→hook per-session control policy, written by the extension to
 * `<controlDir>/<sessionId>.json` and read by the blocking hook. `control` is
 * the operator's take-control toggle; `globalAutoApprove` mirrors VS Code's
 * global auto-approve setting (⇒ defer, as VS Code would auto-approve); `allow`
 * is the operator-grown per-session allow-list (the reachable analog of VS
 * Code's session `permissions.allow`). Absent/junk ⇒ NO_CONTROL (never block).
 */
export const controlPolicySchema = z.object({
  control: z.boolean(),
  globalAutoApprove: z.boolean().optional(),
  allow: z.array(z.string()).optional(),
});
export type ControlPolicy = z.infer<typeof controlPolicySchema>;

/** The safe default: not in control, so the hook stays a pure notifier. */
export const NO_CONTROL: ControlPolicy = { control: false };

/**
 * The per-session control DIR — a fixed sibling of the spool dir so the single
 * `CLOAKCODE_SPOOL` override (dev-server / isolated rig) moves both together and
 * they can never point at different environments.
 */
export function controlDirFor(spoolDir: string): string {
  return path.join(path.dirname(spoolDir), "control");
}

/** The default control dir (`~/.cloakcode/control`). */
export function defaultControlDir(): string {
  return controlDirFor(defaultSpoolDir());
}

/** Path of the policy file for one session. */
export function controlPolicyPath(dir: string, sessionId: string): string {
  return path.join(dir, `${sessionId}.json`);
}

/** Read a session's control policy, tolerant of an absent / partial / junk file. */
export async function readControlPolicy(
  dir: string,
  sessionId: string,
): Promise<ControlPolicy> {
  try {
    const raw = JSON.parse(
      await fs.readFile(controlPolicyPath(dir, sessionId), "utf8"),
    );
    const parsed = controlPolicySchema.safeParse(raw);
    return parsed.success ? parsed.data : NO_CONTROL;
  } catch {
    return NO_CONTROL;
  }
}

/** Write (or overwrite) a session's control policy. */
export function writeControlPolicy(
  dir: string,
  sessionId: string,
  policy: ControlPolicy,
): void {
  fsSync.mkdirSync(dir, { recursive: true });
  fsSync.writeFileSync(
    controlPolicyPath(dir, sessionId),
    JSON.stringify(policy),
  );
}

/** The hook's action for one PreToolUse, given the session's policy. */
export type PreToolAction = "notify" | "defer" | "block";

/**
 * Session permission levels that mean "VS Code auto-approves this call" — the
 * per-request `permissionLevel` from the debug-log (docs/02 §4.15). `autoApprove`
 * is the "Bypass Approvals" status-bar toggle; `autopilot` auto-approves + auto-
 * answers. `default`/`assisted` still prompt, so they are NOT here.
 */
export const AUTO_APPROVE_LEVELS: ReadonlySet<string> = new Set([
  "autoApprove",
  "autopilot",
]);

/**
 * Decide what the PreToolUse hook does with a tool call — the whole point of
 * "only block if VS Code would have blocked":
 * - interactive question tools (`ask`/`confirm`/…) → `notify` (surfaced as a
 *   question, answered via `session.respond` text; never an allow/deny),
 * - not in control, or VS Code would auto-approve — global auto-approve setting,
 *   the session's own `permissionLevel` (Bypass Approvals / autopilot), or the
 *   tool is an allowed exception — → `defer` (emit `{}`, native path unchanged),
 * - otherwise, while in control → `block` (hold for a remote allow/deny).
 *
 * `permissionLevel` is the session-level state that actually drives approval; it
 * isn't in the hook stdin but is read live from the debug-log. VS Code's
 * path/shell auto-approve rules (read-in-workdir, tree-sitter shell) are
 * deliberately NOT replicated (YAGNI/DRY) — those surface unless allow-listed.
 * See docs/02 §4.15.
 */
export function preToolAction(
  policy: ControlPolicy,
  toolName: string,
  permissionLevel?: string,
): PreToolAction {
  if (isInteractiveTool(toolName)) return "notify";
  if (!policy.control) return "defer";
  if (policy.globalAutoApprove) return "defer";
  if (permissionLevel && AUTO_APPROVE_LEVELS.has(permissionLevel))
    return "defer";
  if (policy.allow?.includes(toolName)) return "defer";
  return "block";
}

/**
 * Derive the debug-log `main.jsonl` from the hook's `transcript_path` + session
 * id — they share the standard Copilot layout
 * (`…/GitHub.copilot-chat/{transcripts/<id>.jsonl, debug-logs/<id>/main.jsonl}`).
 * The debug-log records the per-request `permissionLevel` the stdin omits.
 */
export function debugLogFromTranscript(
  transcriptPath: string,
  sessionId: string,
): string {
  return path.join(
    path.dirname(path.dirname(transcriptPath)),
    "debug-logs",
    sessionId,
    "main.jsonl",
  );
}

/**
 * Extract the LAST `permissionLevel` recorded in a chunk of debug-log text
 * (`…"permissionLevel":"<level>"…`, tolerant of JSON-in-JSON escaping). Pure.
 */
export function parsePermissionLevel(text: string): string | undefined {
  const re =
    /permissionLevel[\\"]*:[\\"]*(default|assisted|autoApprove|autopilot)/g;
  let last: string | undefined;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) last = m[1];
  return last;
}

/**
 * Read the session's CURRENT permission level from the tail of its (possibly
 * huge) debug-log — only the last `tailBytes` are read via a seek, never the
 * whole file. Best-effort: any failure (missing/opt-out debug-log, junk) →
 * `undefined`, so the hook safely falls back to the policy signals.
 */
export async function readLatestPermissionLevel(
  debugLogFile: string,
  tailBytes = 512 * 1024,
): Promise<string | undefined> {
  try {
    const handle = await fs.open(debugLogFile, "r");
    try {
      const { size } = await handle.stat();
      const start = Math.max(0, size - tailBytes);
      const len = size - start;
      if (len <= 0) return undefined;
      const buf = Buffer.allocUnsafe(len);
      await handle.read(buf, 0, len, start);
      return parsePermissionLevel(buf.toString("utf8"));
    } finally {
      await handle.close();
    }
  } catch {
    return undefined;
  }
}

/** Path of the on-disk approval verdict for a (raw or base) toolCallId. */
export function decisionEntryPath(dir: string, toolCallId: string): string {
  return path.join(dir, `${baseToolCallId(toolCallId)}.decision`);
}

/** Read the operator's verdict for a pending tool call, if one was written. */
export async function readDecision(
  dir: string,
  toolCallId: string,
): Promise<Decision | undefined> {
  try {
    const raw = JSON.parse(
      await fs.readFile(decisionEntryPath(dir, toolCallId), "utf8"),
    );
    const parsed = z.object({ decision: decisionSchema }).safeParse(raw);
    return parsed.success ? parsed.data.decision : undefined;
  } catch {
    return undefined;
  }
}

/** Write the operator's verdict for a pending tool call (the bridge's side). */
export function writeDecision(
  dir: string,
  toolCallId: string,
  decision: Decision,
): void {
  fsSync.mkdirSync(dir, { recursive: true });
  fsSync.writeFileSync(
    decisionEntryPath(dir, toolCallId),
    JSON.stringify({ decision }),
  );
}

/**
 * Poll `read()` every `intervalMs` until it yields a verdict or `timeoutMs`
 * elapses (⇒ `undefined`, i.e. fall through to VS Code's native approval).
 * Clock + sleep are injectable so the blocking loop is unit-tested without wall
 * time. The hook holds the tool call for the whole wait (Copilot blocks on the
 * hook for its configured `timeout`).
 */
export async function awaitDecision(opts: {
  read: () => Promise<Decision | undefined>;
  timeoutMs: number;
  intervalMs: number;
  sleep?: (ms: number) => Promise<void>;
  now?: () => number;
}): Promise<Decision | undefined> {
  const sleep =
    opts.sleep ?? ((ms: number) => new Promise((r) => setTimeout(r, ms)));
  const now = opts.now ?? Date.now;
  const start = now();
  for (;;) {
    const d = await opts.read();
    if (d) return d;
    if (now() - start >= opts.timeoutMs) return undefined;
    await sleep(opts.intervalMs);
  }
}

/**
 * A core carousel answer value (`IChatQuestionAnswerValue`). The shape must
 * match the question TYPE or VS Code won't RENDER the choice (the tool result is
 * type-tolerant, but the carousel display is not): `singleSelect` uses
 * `selectedValue`, `multiSelect` uses `selectedValues`, freeform uses
 * `freeformValue` (`askQuestionsTool.ts::convertCarouselAnswers`).
 */
export interface CarouselAnswerValue {
  selectedValue?: string;
  selectedValues?: string[];
  freeformValue?: string;
}

/**
 * Build the core carousel answer record for `_chat.notifyQuestionCarouselAnswer`
 * from CloakCode's per-question `answers` (docs/02 §4.16), keyed by the internal
 * question id `${resolveId}:${index}`. Picks the value shape by intent so VS
 * Code renders it: a typed freeform value → `freeformValue`; a single chosen
 * option → `selectedValue` (singular = single-select); multiple →
 * `selectedValues`. Pure.
 */
export function buildCarouselAnswers(
  resolveId: string,
  answers: readonly QuestionAnswer[],
): Record<string, CarouselAnswerValue> {
  const record: Record<string, CarouselAnswerValue> = {};
  answers.forEach((a, i) => {
    const key = `${resolveId}:${i}`;
    if (a.multiSelect) {
      record[key] = {
        selectedValues: a.selected,
        ...(a.freeText ? { freeformValue: a.freeText } : {}),
      };
    } else if (a.freeText) {
      record[key] = { freeformValue: a.freeText };
    } else {
      const only = a.selected[0];
      record[key] =
        only !== undefined
          ? { selectedValue: only }
          : { selectedValues: a.selected };
    }
  });
  return record;
}

/**
 * Strip the `__vscode-<n>` suffix the hook receives so the id matches the
 * transcript's `toolCallId` (docs/02 §4.6 — this is the dedup join key) and
 * yields a stable, filesystem-safe spool filename.
 */
export function baseToolCallId(raw: string): string {
  const i = raw.indexOf("__vscode-");
  return i === -1 ? raw : raw.slice(0, i);
}

/** Path of the spool entry file for a (raw or base) toolCallId. */
export function spoolEntryPath(dir: string, toolCallId: string): string {
  return path.join(dir, `${baseToolCallId(toolCallId)}.json`);
}

/**
 * Extract the routing keys the hook cares about from a `PreToolUse`/`PostToolUse`
 * stdin payload (`{ session_id, tool_name, tool_use_id, tool_input }`). Shared by
 * every record builder so the field names live in exactly one place.
 */
export function hookRouting(stdin: unknown): {
  sessionId: string;
  toolName: string;
  rawId: string;
  input: unknown;
  transcriptPath: string;
} {
  const s = (typeof stdin === "object" && stdin ? stdin : {}) as Record<
    string,
    unknown
  >;
  return {
    sessionId: String(s["session_id"] ?? ""),
    toolName: String(s["tool_name"] ?? ""),
    rawId: String(s["tool_use_id"] ?? ""),
    input: s["tool_input"] ?? null,
    transcriptPath: String(s["transcript_path"] ?? ""),
  };
}

/**
 * Build the pending record for a `PreToolUse` invocation, or `undefined` when
 * the event lacks routing keys. Pure so the hook's I/O shell stays trivial and
 * tested. (`PostToolUse` needs no record — the hook just deletes the file.)
 */
export function pendingRecord(
  stdin: unknown,
  ts: string,
): SpoolRecord | undefined {
  const { sessionId, toolName, rawId, input } = hookRouting(stdin);
  // Only interactive tools are blockers worth surfacing (docs/02 §4.6). Skipping
  // the rest means non-blocker tool calls (read_file, grep, …) never touch the
  // spool — no write/delete churn, and the overlay can't flicker a non-blocker.
  if (!sessionId || !rawId || !isInteractiveTool(toolName)) return undefined;
  return {
    sessionId,
    toolCallId: baseToolCallId(rawId),
    toolName,
    input,
    ts,
    resolveId: rawId,
  };
}

/** The base toolCallId a hook event refers to (for the delete path). */
export function eventToolCallId(stdin: unknown): string | undefined {
  const { rawId } = hookRouting(stdin);
  return rawId ? baseToolCallId(rawId) : undefined;
}

/**
 * Like {@link pendingRecord} but for the BLOCKING path: records ANY tool (a tool
 * approval isn't limited to interactive questions) and flags `awaitingDecision`
 * so the overlay renders approve/deny. Pure. Used only while the session is in
 * control and {@link preToolAction} returned `block`.
 */
export function blockingRecord(
  stdin: unknown,
  ts: string,
): SpoolRecord | undefined {
  const { sessionId, toolName, rawId, input } = hookRouting(stdin);
  if (!sessionId || !rawId) return undefined;
  return {
    sessionId,
    toolCallId: baseToolCallId(rawId),
    toolName,
    input,
    ts,
    awaitingDecision: true,
    resolveId: rawId,
  };
}

/** Read all valid spool records from the spool directory (tolerant of junk). */
export async function readSpoolDir(dir: string): Promise<SpoolRecord[]> {
  let names: string[];
  try {
    names = await fs.readdir(dir);
  } catch {
    return [];
  }
  const out: SpoolRecord[] = [];
  for (const name of names) {
    if (!name.endsWith(".json")) continue;
    let raw: unknown;
    try {
      raw = JSON.parse(await fs.readFile(path.join(dir, name), "utf8"));
    } catch {
      continue; // partial write / junk — skip, a later refresh will catch it
    }
    const parsed = spoolRecordSchema.safeParse(raw);
    if (parsed.success) out.push(parsed.data);
  }
  return out;
}

/** Collect the base `toolCallId`s already present in a transcript body. */
export function transcriptToolCallIds(content: string): Set<string> {
  const ids = new Set<string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    let raw: { type?: string; data?: { toolCallId?: unknown } };
    try {
      raw = JSON.parse(trimmed);
    } catch {
      continue;
    }
    if (raw.type === "tool.execution_start" && raw.data?.toolCallId != null) {
      ids.add(baseToolCallId(String(raw.data.toolCallId)));
    }
  }
  return ids;
}

/**
 * A spool record is _retired_ once its tool has landed in the transcript (its
 * base `toolCallId` appears there). Per §4.6 interactive events flush at
 * completion, so transcript presence ⟹ the tool finished — the single source of
 * truth for "this blocker is done", used both to drop it from the overlay and to
 * self-heal a spool file whose `PostToolUse` delete failed.
 */
export function isRetired(
  record: SpoolRecord,
  transcriptIds: ReadonlySet<string>,
): boolean {
  return transcriptIds.has(baseToolCallId(record.toolCallId));
}

/**
 * Compute the live-pending overlay for one session: every spool record for that
 * session (each file = a live blocker), minus any already flushed to the
 * transcript (belt-and-suspenders dedup so a missed delete can't strand a card).
 * Replace-snapshot semantics — the caller pushes the whole list.
 */
export function computePendingBlockers(
  records: readonly SpoolRecord[],
  sessionId: string,
  transcriptIds: ReadonlySet<string> = new Set(),
): PendingBlocker[] {
  const pending = new Map<string, PendingBlocker>();
  for (const r of records) {
    if (r.sessionId !== sessionId) continue;
    if (isRetired(r, transcriptIds)) continue;
    const base = baseToolCallId(r.toolCallId);
    pending.set(base, {
      toolCallId: base,
      toolName: r.toolName,
      createdAt: r.ts,
      ...(r.awaitingDecision ? { awaitingDecision: true } : {}),
      ...(r.resolveId ? { resolveId: r.resolveId } : {}),
      ...(isInteractiveTool(r.toolName)
        ? { confirmations: toConfirmations(`conf-${base}`, r.input) }
        : { input: r.input ?? null }),
    });
  }
  return [...pending.values()];
}

export type PendingSink = (blockers: PendingBlocker[]) => void;

async function readOrEmpty(file: string): Promise<string> {
  try {
    return await fs.readFile(file, "utf8");
  } catch {
    return "";
  }
}

/**
 * Tails the (global) hook spool DIRECTORY and the subscribed session's
 * transcript, and emits the live-pending overlay as a replace-snapshot for that
 * session. Mirrors `SessionFollower`'s hybrid `fs.watch` + poll strategy
 * (dev-container overlays drop inotify events) and serializes on a promise
 * queue. Emits only when the snapshot changes. Recompute is triggered by EITHER
 * the spool dir or the transcript changing.
 */
export class SpoolFollower {
  private watchers: fsSync.FSWatcher[] = [];
  private poller: ReturnType<typeof setInterval> | undefined;
  private queue: Promise<void> = Promise.resolve();
  private stopped = false;
  private last: string | undefined;
  private readonly pollIntervalMs: number;

  constructor(
    private readonly spoolDir: string,
    private readonly transcriptFile: string,
    private readonly sessionId: string,
    private readonly sink: PendingSink,
    options: { pollIntervalMs?: number } = {},
  ) {
    this.pollIntervalMs = options.pollIntervalMs ?? 400;
  }

  async start(): Promise<void> {
    await this.refresh();
    if (this.stopped) return;
    for (const target of [this.spoolDir, this.transcriptFile]) {
      try {
        this.watchers.push(fsSync.watch(target, () => void this.refresh()));
      } catch {
        // dir/file may not exist yet; the poll fallback covers it
      }
    }
    if (this.pollIntervalMs > 0) {
      this.poller = setInterval(() => void this.refresh(), this.pollIntervalMs);
      this.poller.unref();
    }
  }

  refresh(): Promise<void> {
    this.queue = this.queue.then(() => this.pump());
    return this.queue;
  }

  private async pump(): Promise<void> {
    if (this.stopped) return;
    const records = await readSpoolDir(this.spoolDir);
    if (this.stopped) return;
    const mine = records.filter((r) => r.sessionId === this.sessionId);

    // Fast path: no spool file for this session → nothing is pending, so skip
    // reading and parsing the (potentially large) transcript entirely.
    if (mine.length === 0) {
      this.emit([]);
      return;
    }

    const transcriptIds = transcriptToolCallIds(
      await readOrEmpty(this.transcriptFile),
    );
    if (this.stopped) return;

    // Self-heal: a spool file whose tool already completed (its toolCallId is in
    // the transcript — §4.6, interactive events land there at completion) is
    // stale; the hook's PostToolUse delete must have failed. Unlink it so it
    // stops costing dedup compute on every pump instead of lingering forever.
    // (Idempotent under concurrent followers; the dedup below already hides it.)
    const stale = mine.filter((r) => isRetired(r, transcriptIds));
    await Promise.all(
      stale.map((r) =>
        fs
          .rm(spoolEntryPath(this.spoolDir, r.toolCallId), { force: true })
          .catch(() => {
            // best-effort — the transcript-subtraction dedup keeps it invisible
          }),
      ),
    );
    if (this.stopped) return;

    this.emit(computePendingBlockers(mine, this.sessionId, transcriptIds));
  }

  private emit(blockers: PendingBlocker[]): void {
    const snapshot = JSON.stringify(blockers);
    if (snapshot === this.last) return;
    this.last = snapshot;
    this.sink(blockers);
  }

  stop(): void {
    this.stopped = true;
    for (const w of this.watchers) w.close();
    this.watchers = [];
    if (this.poller) {
      clearInterval(this.poller);
      this.poller = undefined;
    }
  }
}
